name: gvxr-tutorials
channels:
    - conda-forge
    - intel
    - astra-toolbox
    - ccpi
dependencies:
    - bqplot=0.12.33
    - branca=0.5.0
    - ipycanvas=0.12.0
    - ipycytoscape=1.3.3
    - ipydatagrid=1.1.12
    - ipyevents=2.0.1
    - ipygany=0.5.0
    - ipyleaflet=0.16.0
    - ipympl=0.9.1
    - ipytree=0.2.1
    - ipyvolume=0.6.0a8
    - ipyvuetify=1.8.2
    - ipywidgets=7.7.0
    - jupyterlab=3.4
    - mpl-interactions=0.22.0
    - numpy
    - orjson=3.7.7  # Added 2022 for one of the ipycanvas examples
    - pandas
    - pip
    - python=3.10
    - pythreejs=2.3.0
    - pyvista=0.34.0
    - requests
    - scikit-image
    - scipy
    - sidecar=0.5.1
    - vtk



    
#     # - ipython
#     # - ipykernel
#     - npm
#     - nodejs
#     # - traittypes=0.2.1
#     # - numpy=1.24
#     # - pandas
#     # - libtiff
#     - vtk
#     - jupyterlab>=3
#     - ipywidgets>=7.6
# #    - cma
# #    - tomopy
# #- scikit-learn
#     - scikit-image
#       #- scipy
# #    - imageio
    - SimpleITK
#       #- numpy-stl
#     - gputil
#     # - python-kaleido
#       #- plotly
#     - matplotlib
#     - ipympl
#     - py-cpuinfo
#     #- unlzw3
    - cil=22.2.0
    - tigre=2.2
    - astra-toolbox
    - k3d
#     - pip
    - pip:
#        - viewscad
        # - xpecgen
        #- git+https://bitbucket.org/spekpy/spekpy_release.git
          #- pymoo==0.5.0
#        - chart_studio
        - gvxr
          #- opencv-python
          #- unlzw3
        # - npm
